#include <net/codemap.h>

/**********************************************************************
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT CHANGE IT MANUALLY!
 **********************************************************************/

/**
 * This table contains all 8-bit numbers which have
 * exactly 4 bits set and 4 bits unset. Such numbers are called codes
 * because encoder uses them for passing messages over L3 cache.
 */
static const cncode_t index_to_code_map[] = {
     15,  23,  27,  29,  30,  39,  43,  45,
     46,  51,  53,  54,  57,  58,  60,  71,
     75,  77,  78,  83,  85,  86,  89,  90,
     92,  99, 101, 102, 105, 106, 108, 113,
    114, 116, 120, 135, 139, 141, 142, 147,
    149, 150, 153, 154, 156, 163, 165, 166,
    169, 170, 172, 177, 178, 180, 184, 195,
    197, 198, 201, 202, 204, 209, 210, 212,
    216, 225, 226, 228, 232, 240,
};

/**
 * This table is a reverse of the table above and allows to find code's
 * number (index)  * in the table above.<F12>
 * Number -1 means there is no such code and equals NO_SUCH_CODE constant
 * defined in net/codemap.h file.
 */
static const int code_to_index_map[] = {
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,   0,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,   1,
     -1,  -1,  -1,   2,  -1,   3,   4,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,   5,
     -1,  -1,  -1,   6,  -1,   7,   8,  -1,
     -1,  -1,  -1,   9,  -1,  10,  11,  -1,
     -1,  12,  13,  -1,  14,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  15,
     -1,  -1,  -1,  16,  -1,  17,  18,  -1,
     -1,  -1,  -1,  19,  -1,  20,  21,  -1,
     -1,  22,  23,  -1,  24,  -1,  -1,  -1,
     -1,  -1,  -1,  25,  -1,  26,  27,  -1,
     -1,  28,  29,  -1,  30,  -1,  -1,  -1,
     -1,  31,  32,  -1,  33,  -1,  -1,  -1,
     34,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  35,
     -1,  -1,  -1,  36,  -1,  37,  38,  -1,
     -1,  -1,  -1,  39,  -1,  40,  41,  -1,
     -1,  42,  43,  -1,  44,  -1,  -1,  -1,
     -1,  -1,  -1,  45,  -1,  46,  47,  -1,
     -1,  48,  49,  -1,  50,  -1,  -1,  -1,
     -1,  51,  52,  -1,  53,  -1,  -1,  -1,
     54,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  55,  -1,  56,  57,  -1,
     -1,  58,  59,  -1,  60,  -1,  -1,  -1,
     -1,  61,  62,  -1,  63,  -1,  -1,  -1,
     64,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  65,  66,  -1,  67,  -1,  -1,  -1,
     68,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     69,
};

cncode_t index_to_code(int index) {
    static const int i2c_size = (sizeof(index_to_code_map) / sizeof(index_to_code_map[0]));
    if (index >= i2c_size || index < 0) {
        return NO_SUCH_INDEX;
    }
    return index_to_code_map[index];
}

int code_to_index(cncode_t code) {
    static const unsigned c2i_size = (sizeof(code_to_index_map) / sizeof(code_to_index_map[0]));
    if ((unsigned)code >= c2i_size) {
        return NO_SUCH_CODE;
    }
    return code_to_index_map[code];
}

